spring:
  datasource:
    url: jdbc:mysql://localhost/crm
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html
#  mvc:
#    log-request-details: true
#debug: true
